# Project on Kidney Disease CKD dataset

IMPORTING THE LIBRARIES

In [1]:
#####  Imported the necessary dependencies 
import pandas as pd 
import numpy as np

LOADING THE DATASET

In [2]:
Data=pd.read_csv(r"C:\Users\harik\OneDrive\Desktop\VCUBE Works\Ckd.rpoject\Kidney-Dataset(CKD).csv") # To read the datset

pd.set_option('display.max_columns', None)  # To display all columns
pd.set_option('display.max_rows', None)   # To display all rows

Data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.20,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.80,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.80,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.80,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.40,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,25.0,1.10,142.0,3.2,12.2,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,54.0,24.00,104.0,4.0,12.4,36,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.10,NaN,NaN,12.4,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.90,NaN,NaN,10.8,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.20,114.0,3.7,9.5,29,12100,3.7,yes,yes,no,poor,no,yes,ckd


BASIC DATASET INFORMATION AND OPERATIONS

In [3]:
print(Data.shape)  # 400 patients and 26 disease calculation features
print(Data.info()) # There are categorical and numerical data
print(Data.columns) # object datatype

(400, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              400 non-null    int64  
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object 
 7   pc              335 non-null    object 
 8   pcc             396 non-null    object 
 9   ba              396 non-null    object 
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object 
 17  wc              295 non-n

In [4]:
print(Data.isnull().sum())  # check for null values

print(Data['classification'].value_counts())


id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64
classification
ckd       248
notckd    150
ckd\t       2
Name: count, dtype: int64


IMPUTATION-- Handling null values

In [5]:
Data.head(20)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,25.0,1.1,142.0,3.2,12.2,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,54.0,24.0,104.0,4.0,12.4,36,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.1,NaN,NaN,12.4,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.9,NaN,NaN,10.8,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.2,114.0,3.7,9.5,29,12100,3.7,yes,yes,no,poor,no,yes,ckd


In [6]:
# seperating the categorical and numerical data

num_columns = Data.select_dtypes(include=['int64','float64']).columns

cat_columns = Data.select_dtypes(include=['object']).columns

print(num_columns)
print(cat_columns)

# Missing values handling
# Numerical → median
for col in num_columns:
    Data[col].fillna(Data[col].median(), inplace=True)

# Categorical → mode
for col in cat_columns:
    Data[col].fillna(Data[col].mode()[0], inplace=True)





Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo'],
      dtype='object')
Index(['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')


In [7]:
Data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,normal,normal,notpresent,notpresent,121.0,36.0,1.20,138.0,4.4,15.40,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,121.0,18.0,0.80,138.0,4.4,11.30,38,6000,5.2,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.80,138.0,4.4,9.60,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.80,111.0,2.5,11.20,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.40,138.0,4.4,11.60,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,normal,normal,notpresent,notpresent,74.0,25.0,1.10,142.0,3.2,12.20,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,100.0,54.0,24.00,104.0,4.0,12.40,36,9800,5.2,no,no,no,good,no,no,ckd
7,7,24.0,80.0,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.10,138.0,4.4,12.40,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.90,138.0,4.4,10.80,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.20,114.0,3.7,9.50,29,12100,3.7,yes,yes,no,poor,no,yes,ckd


ENCODING THE TARGET VARIABLE AND CAT COLUMNS

In [8]:
# Target variable--Classification Column encoding using LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Data['classification'] = le.fit_transform(Data['classification']) #for Target variable


#Categrical data is converted to numerical using LabelEncoder
Data['rbc'] = le.fit_transform(Data['rbc'])
Data['pc'] = le.fit_transform(Data['pc'])
Data['pcc'] = le.fit_transform(Data['pcc'])
Data['ba'] = le.fit_transform(Data['ba'])
Data['htn'] = le.fit_transform(Data['htn'])
Data['dm'] = le.fit_transform(Data['cad'])
Data['appet'] = le.fit_transform(Data['appet'])
Data['pe'] = le.fit_transform(Data['pe'])
Data['pcv'] = le.fit_transform(Data['pcv'])
Data['wc'] = le.fit_transform(Data['wc'])
Data['rc'] = le.fit_transform(Data['rc'])
Data['cad'] = le.fit_transform(Data['cad'])
Data['ane'] = le.fit_transform(Data['ane'])


Data.head()







,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,1,1,0,0,121.0,36.0,1.2,138.0,4.4,15.4,32,72,34,1,1,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,1,1,0,0,121.0,18.0,0.8,138.0,4.4,11.3,26,56,34,0,1,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,423.0,53.0,1.8,138.0,4.4,9.6,19,70,34,0,1,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,117.0,56.0,3.8,111.0,2.5,11.2,20,62,19,1,1,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,106.0,26.0,1.4,138.0,4.4,11.6,23,68,27,0,1,1,0,0,0,0


In [9]:
Data.dtypes



id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int32
pc                  int32
pcc                 int32
ba                  int32
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                 int32
wc                  int32
rc                  int32
htn                 int32
dm                  int32
cad                 int32
appet               int32
pe                  int32
ane                 int32
classification      int32
dtype: object

OUTLIERS DETECTION AND REMOVAL

In [10]:
print(Data.head())
print(Data.columns)
print(num_columns)


   id   age    bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu   sc    sod  \
0   0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  36.0  1.2  138.0   
1   1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  121.0  18.0  0.8  138.0   
2   2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  53.0  1.8  138.0   
3   3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  56.0  3.8  111.0   
4   4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  26.0  1.4  138.0   

   pot  hemo  pcv  wc  rc  htn  dm  cad  appet  pe  ane  classification  
0  4.4  15.4   32  72  34    1   1    1      0   0    0               0  
1  4.4  11.3   26  56  34    0   1    1      0   0    0               0  
2  4.4   9.6   19  70  34    0   1    1      1   0    1               0  
3  2.5  11.2   20  62  19    1   1    1      1   1    1               0  
4  4.4  11.6   23  68  27    0   1    1      0   0    0               0  
Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba',

In [11]:
# Outliers detection using IQR and removing outliers using IQR

Q1 = Data[num_columns].quantile(0.25)
Q3 = Data[num_columns].quantile(0.75)
IQR = Q3 - Q1

outliers = ((Data[num_columns] < (Q1 - 1.5 * IQR)) | 
            (Data[num_columns] > (Q3 + 1.5 * IQR)))


outliers.sum()

for col in num_columns:
    Q1 = Data[col].quantile(0.25)
    Q3 = Data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    Data[col] = Data[col].clip(lower, upper)

Data.head()




,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.0200,1.0,0.0,1,1,0,0,121.0,36.0,1.2,138.0,4.4,15.4,32,72,34,1,1,1,0,0,0,0
1,1,9.0,55.0,1.0200,4.0,0.0,1,1,0,0,121.0,18.0,0.8,138.0,4.4,11.3,26,56,34,0,1,1,0,0,0,0
2,2,62.0,80.0,1.0100,2.0,0.0,1,1,0,0,223.5,53.0,1.8,138.0,4.4,9.6,19,70,34,0,1,1,1,0,1,0
3,3,48.0,70.0,1.0075,4.0,0.0,1,0,1,0,117.0,56.0,3.8,126.0,2.8,11.2,20,62,19,1,1,1,1,1,1,0
4,4,51.0,80.0,1.0100,2.0,0.0,1,1,0,0,106.0,26.0,1.4,138.0,4.4,11.6,23,68,27,0,1,1,0,0,0,0


In [39]:
outliers.sum()

id       0
age     10
bp      36
sg       7
al       0
su      61
bgr     53
bu      41
sc      53
sod     18
pot     14
hemo     2
dtype: int64

SEPERATING THE FEATURES AND TARGET



In [13]:
X = Data.drop('classification', axis=1)
Y = Data['classification']


In [14]:
X

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,0,48.0,80.0,1.0200,1.0,0.0,1,1,0,0,121.0,36.000,1.2000,138.0,4.4,15.40,32,72,34,1,1,1,0,0,0
1,1,9.0,55.0,1.0200,4.0,0.0,1,1,0,0,121.0,18.000,0.8000,138.0,4.4,11.30,26,56,34,0,1,1,0,0,0
2,2,62.0,80.0,1.0100,2.0,0.0,1,1,0,0,223.5,53.000,1.8000,138.0,4.4,9.60,19,70,34,0,1,1,1,0,1
3,3,48.0,70.0,1.0075,4.0,0.0,1,0,1,0,117.0,56.000,3.8000,126.0,2.8,11.20,20,62,19,1,1,1,1,1,1
4,4,51.0,80.0,1.0100,2.0,0.0,1,1,0,0,106.0,26.000,1.4000,138.0,4.4,11.60,23,68,27,0,1,1,0,0,0
5,5,60.0,90.0,1.0150,3.0,0.0,1,1,0,0,74.0,25.000,1.1000,142.0,3.2,12.20,27,72,25,1,1,1,0,1,0
6,6,68.0,70.0,1.0100,0.0,0.0,1,1,0,0,100.0,54.000,5.4625,126.0,4.0,12.40,24,90,34,0,1,1,0,0,0
7,7,24.0,80.0,1.0150,2.0,0.0,1,0,0,0,223.5,31.000,1.1000,138.0,4.4,12.40,32,64,31,0,1,1,0,1,0
8,8,52.0,95.0,1.0150,3.0,0.0,1,0,1,0,138.0,60.000,1.9000,138.0,4.4,10.80,21,88,21,1,1,1,0,0,1
9,9,53.0,90.0,1.0200,2.0,0.0,0,0,1,0,70.0,107.000,5.4625,126.0,3.7,9.50,17,18,17,1,1,1,1,0,1


In [15]:
Y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

TRAIN AND TEST SPLIT

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=45,stratify=Y)   

In [17]:
X_train.shape

(320, 25)

In [18]:
Y_train.shape

(320,)

In [19]:
X_test.shape

(80, 25)

In [20]:
Y_test.shape


(80,)

In [21]:
feature_names = X_train.columns
feature_names

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane'],
      dtype='object')

FEATURE SCALING - STANDARDIZATION

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)
print(X_test_scaled)

[[ 1.017551    0.54661008 -0.51063436 ... -0.50487816 -0.4951123
  -0.42521972]
 [-1.40019682 -0.29722629  1.72776285 ... -0.50487816 -0.4951123
   2.35172538]
 [ 0.95623131  0.24523994 -1.40599325 ... -0.50487816 -0.4951123
  -0.42521972]
 ...
 [-0.94467911  0.78770618 -0.51063436 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 0.49195365 -0.59859642  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [-0.0949634   0.18496592 -0.51063436 ...  1.98067588 -0.4951123
  -0.42521972]]
[[ 1.41174901  0.90825423  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 1.65702777 -0.96024058  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 0.10651559  0.96852826  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 ...
 [-0.69940035 -1.08078864 -0.51063436 ... -0.50487816 -0.4951123
   2.35172538]
 [-1.63671563 -0.71914448  0.38472452 ... -0.50487816 -0.4951123
   2.35172538]
 [ 0.43063395 -1.74380293  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]]


DIMENSIONALITY REDUCTION ---PRINCIPAL COMPONENT ANALYSIS

In [23]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)   # 95% variance

X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
print(X_train_pca)
print(X_test_pca)

[[-3.13674169 -0.53035348  0.35472891 ... -0.26380792 -0.44820023
  -0.41875094]
 [ 1.49613047  0.97474167 -1.72690312 ...  0.42269017 -0.03522404
  -0.55064148]
 [-2.98296275 -0.59008697 -0.11738637 ...  0.40938898  0.39568746
   0.11296495]
 ...
 [ 0.10573218  0.37019135 -0.2192586  ... -0.78708264 -0.10444817
  -0.24814117]
 [-2.49307682  0.15323774  0.2597103  ... -0.13270848  0.10155322
   0.1031579 ]
 [ 3.36199854  0.81428278 -1.03884323 ...  0.14869636 -0.81540459
   1.52666268]]
[[-2.79880179 -0.57111005 -0.18394585 ... -0.58544794 -0.31746267
   0.20655631]
 [-3.44272335 -0.11417733  0.36139045 ...  0.43114577  0.43143024
   0.39902982]
 [ 0.43051059  0.32353142  0.25096336 ... -1.42721585  1.60462496
   0.23022096]
 ...
 [ 2.03199356  1.07929726 -2.26661419 ...  1.32228981  0.4211985
  -0.8481531 ]
 [ 3.77853117  1.41446378 -1.91014507 ...  1.86506108 -1.38043718
   0.51261574]
 [-3.55964589 -0.02953858 -0.02296169 ...  0.57944786 -0.82083275
  -0.58152673]]


SCALING THE DATA FOR NON-NEG VALUES FOR CHI2 ANALYSIS

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_data = scaler.fit_transform(X_train_pca)
X_test_data = scaler.transform(X_test_pca)
print(X_train_data)
print(X_test_data)

[[0.06045171 0.42826182 0.47323922 ... 0.43822504 0.37840386 0.3892208 ]
 [0.44228642 0.5667856  0.21591237 ... 0.57506782 0.47945105 0.3556155 ]
 [0.07312595 0.42276415 0.41487735 ... 0.57241643 0.58488665 0.52470035]
 ...
 [0.32769178 0.51114487 0.40228413 ... 0.33391831 0.46251326 0.43269164]
 [0.11350165 0.49117721 0.46149323 ... 0.46435768 0.51291777 0.52220154]
 [0.5960686  0.55201752 0.30096885 ... 0.52045139 0.28855614 0.88490611]]
[[0.08830423 0.42451073 0.40664941 ... 0.37411107 0.41039278 0.54854714]
 [0.03523313 0.46656524 0.47406271 ... 0.57675331 0.59363221 0.59758878]
 [0.35445955 0.50685045 0.46041195 ... 0.20631765 0.88069    0.55457682]
 ...
 [0.48645149 0.57640854 0.14919446 ... 0.7543891  0.59112871 0.27981047]
 [0.63039863 0.60725611 0.1932604  ... 0.86258216 0.15030372 0.62653012]
 [0.02559654 0.4743551  0.42654993 ... 0.60631504 0.28722797 0.34774604]]


FEATURE SELECTION- SELECTKBEST , CHI2

In [25]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=10)

X_train_selected = selector.fit_transform(X_train_data, Y_train)
X_test_selected = selector.transform(X_test_data)


In [26]:
print(X_train_selected)
print(X_test_selected )

[[0.06045171 0.42826182 0.30941769 ... 0.36846078 0.50331842 0.57234494]
 [0.44228642 0.5667856  0.19667529 ... 0.41872857 0.64717055 0.52316984]
 [0.07312595 0.42276415 0.40159904 ... 0.4702894  0.52747379 0.49740634]
 ...
 [0.32769178 0.51114487 0.51179291 ... 0.78955533 0.44414729 0.54310063]
 [0.11350165 0.49117721 0.29816774 ... 0.52583916 0.53689693 0.4982983 ]
 [0.5960686  0.55201752 0.2666119  ... 0.56141012 0.30066521 0.32681949]]
[[ 0.08830423  0.42451073  0.4835393   0.50512206  0.29471406  0.45870881
   0.33340081  0.46907288  0.5521265   0.60931099]
 [ 0.03523313  0.46656524  0.50189949  0.39710417  0.36382019  0.54077857
   0.38531566  0.4407769   0.49723727  0.49446468]
 [ 0.35445955  0.50685045  0.38805854  0.35481508  0.59152719  0.56741362
   0.25771186  0.54836255  0.69156431  0.48445782]
 [ 0.14942508  0.47707541  0.43892303  0.42656847  0.58610759  0.43469697
   0.43046463  0.43513055  0.44259803  0.52967784]
 [ 0.56977235  0.54159958  0.22572851  0.71097036  0.937

In [27]:
X_train_selected.shape

(320, 10)

In [28]:
X_test_selected .shape

(80, 10)

BEST SELECTED K FEATURES

feature_scores = pd.DataFrame({
    'Feature': feature_names,
    'Chi2_score': selector.scores_
})

feature_sorted = feature_scores.sort_values(
    by='Chi2_score',
    ascending=False
)

print(feature_sorted)


print(len(feature_names))
print(len(selector.scores_))



selected_features = feature_names[selector.get_support()]
print("Selected Features:", list(selected_features))

APPLYING KNN ALGORITHM AND EVALUATION

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [30]:
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

knn.fit(X_train_selected, Y_train)

y_pred = knn.predict(X_test_selected)
print(y_pred)

[2 2 0 2 0 0 0 0 2 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 2 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 0 0 0 2]


In [31]:
accuracy = accuracy_score(Y_test, y_pred)
print("KNN Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))
      
print("Classification Report:\n", classification_report(Y_test, y_pred))

KNN Accuracy: 0.9875
Confusion Matrix:
 [[49  1]
 [ 0 30]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



DECISION TREE ALG AND EVALUATION

In [32]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(criterion='gini',max_depth=5,random_state=42)


decision_tree.fit(X_train_selected, Y_train)

y_pred_dt = decision_tree.predict(X_test_selected)

print(y_pred_dt)




[2 2 0 2 0 0 0 0 0 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 0 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 0 0 0 2]


In [33]:

print("Decision Tree Accuracy:", accuracy_score(Y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_dt))
print("Classification Report:\n", classification_report(Y_test, y_pred_dt))


Decision Tree Accuracy: 0.9875
Confusion Matrix:
 [[50  0]
 [ 1 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        50
           2       1.00      0.97      0.98        30

    accuracy                           0.99        80
   macro avg       0.99      0.98      0.99        80
weighted avg       0.99      0.99      0.99        80



NAIVE BAYES ALG- (Gaussian, multinomial and bernoullis) AND EVALUATION

In [34]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_selected, Y_train)
y_pred_nb = nb.predict(X_test_selected)
print(y_pred_nb)


print("Naive Bayes Accuracy:", accuracy_score(Y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_nb))
print("Classification Report:\n", classification_report(Y_test, y_pred_nb))


[2 2 0 2 0 0 0 0 2 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 0 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 2 0 0 2]
Naive Bayes Accuracy: 0.9875
Confusion Matrix:
 [[49  1]
 [ 0 30]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [35]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train_selected, Y_train)
y_pred_mnb = mnb.predict(X_test_selected)
print(y_pred_mnb)


print("Multinomial NB Accuracy:", accuracy_score(Y_test, y_pred_mnb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_mnb))
print("Classification Report:\n", classification_report(Y_test, y_pred_mnb))



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Multinomial NB Accuracy: 0.625
Confusion Matrix:
 [[50  0]
 [30  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        50
           2       0.00      0.00      0.00        30

    accuracy                           0.62        80
   macro avg       0.31      0.50      0.38        80
weighted avg       0.39      0.62      0.48        80



c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [36]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train_selected, Y_train)
y_pred_bnb = bnb.predict(X_test_selected)
print(y_pred_bnb)

print("Bernoulli NB Accuracy:", accuracy_score(Y_test, y_pred_bnb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_bnb))
print("Classification Report:\n", classification_report(Y_test, y_pred_bnb))




[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Bernoulli NB Accuracy: 0.625
Confusion Matrix:
 [[50  0]
 [30  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        50
           2       0.00      0.00      0.00        30

    accuracy                           0.62        80
   macro avg       0.31      0.50      0.38        80
weighted avg       0.39      0.62      0.48        80



c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


TO COMPARE 3 ALGORITHMS METRICS

In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = ['KNN', 'Decision Tree', 'Naive Bayes']

accuracy = [
    accuracy_score(Y_test, y_pred),
    accuracy_score(Y_test, y_pred_dt),
    accuracy_score(Y_test, y_pred_nb)
]

precision = [
    precision_score(Y_test, y_pred, pos_label=2),
    precision_score(Y_test, y_pred_dt, pos_label=2),
    precision_score(Y_test, y_pred_nb, pos_label=2)
]

recall = [
    recall_score(Y_test, y_pred, pos_label=2),
    recall_score(Y_test, y_pred_dt, pos_label=2),
    recall_score(Y_test, y_pred_nb, pos_label=2)
]

f1 = [
    f1_score(Y_test, y_pred, pos_label=2),
    f1_score(Y_test, y_pred_dt, pos_label=2),
    f1_score(Y_test, y_pred_nb, pos_label=2)
]

comparison_df = pd.DataFrame({
    'Model': models,
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-Score': f1
})

print(comparison_df)


           Model  Accuracy  Precision    Recall  F1-Score
0            KNN    0.9875   0.967742  1.000000  0.983607
1  Decision Tree    0.9875   1.000000  0.966667  0.983051
2    Naive Bayes    0.9875   0.967742  1.000000  0.983607


METRICS- ROC AND AUC

In [41]:
from sklearn.metrics import roc_curve, auc

plt.figure()

# KNN
y_prob = knn.predict_proba(X_test_selected)[:, 1]
fpr_knn, tpr_knn, _ = roc_curve(Y_test, y_prob, pos_label=2)
plt.plot(fpr_knn, tpr_knn, label='KNN')

# Decision Tree
y_prob_dt = decision_tree.predict_proba(X_test_selected)[:, 1]
fpr_dt, tpr_dt, _ = roc_curve(Y_test, y_prob_dt, pos_label=2)
plt.plot(fpr_dt, tpr_dt, label='Decision Tree')

# Naive Bayes
y_prob_nb = nb.predict_proba(X_test_selected)[:, 1]
fpr_nb, tpr_nb, _ = roc_curve(Y_test, y_prob_nb, pos_label=2)
plt.plot(fpr_nb, tpr_nb, label='Naive Bayes')

# Random baseline
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()
plt.show()


NameError: name 'plt' is not defined

This project predicts Chronic Kidney Disease using patient medical data.
Performed data cleaning, handled missing values, encoded categorical variables, applied feature scaling,
 and trained multiple machine learning models like KNN, Decision Tree, and Naive Bayes.
Evaluated them using accuracy, precision, recall, and confusion matrix. The model helps in early CKD detection, which is critical in healthcare

SVM ALGORITHM- 22/12/25

In [ ]:
from sklearn.svm import SVC ##imported svc

svm_method= SVC(kernel="linear")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))







Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [ ]:
svm_method= SVC(kernel="rbf")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [ ]:
svm_method= SVC(kernel="poly")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [ ]:
svm_method= SVC(kernel="sigmoid")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [ ]:

import pickle

pickle.dump(models, open("kidney_model.pkl", "wb"))

print("✅ Model trained and saved as kidney_model.pkl")

✅ Model trained and saved as kidney_model.pkl
